In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd

df = pd.read_csv("Customer Behaviour Analysis.csv")
print(df.head())

   customer_id  age gender item_purchased  category  purchase_amount  \
0            1   55   Male         Blouse  Clothing               53
1            2   19   Male        Sweater  Clothing               64
2            3   50   Male          Jeans  Clothing               73
3            4   21   Male        Sandals  Footwear               90
4            5   45   Male         Blouse  Clothing               49

        location size      color  season  review_rating subscription_status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   shipping_type discount_applied  previous_purchases payment_method  \
0        Express              Yes                  14          Venmo
1        Express              Yes                   2           Cash
2  Free Shipping              Yes                  23    Credit Card
3   Next Day Air              Yes                  49         PayPal
4  Free Shipping              Yes                  31         PayPal

  frequency_of_purchases age_group  purchase_frequency_days
0            Fortnightly    senior                      365
1            Fortnightly     Young                      365
2                 Weekly    senior                      365
3                 Weekly     Young                      365
4               Annually    senior                       14

In [3]:
# Remove spaces from column names
df.columns = df.columns.str.strip()

In [4]:
#check missing values
df.isnull().sum()

customer_id                 0
age                         0
gender                      0
item_purchased              0
category                    0
purchase_amount             0
location                    0
size                        0
color                       0
season                      0
review_rating              37
subscription_status         0
shipping_type               0
discount_applied            0
previous_purchases          0
payment_method              0
frequency_of_purchases      0
age_group                   0
purchase_frequency_days     0
dtype: int64

In [5]:
print(df.columns)

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [6]:
#Fill rating with median
df['review_rating']=df['review_rating'].fillna(df['review_rating'].median())

In [7]:
print(list(df.columns))

['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'previous_purchases', 'payment_method', 'frequency_of_purchases', 'age_group', 'purchase_frequency_days']

In [8]:
#Fill categorial columns with 'Unknown'
categorical_cols = df.select_dtypes(include = ['object']).columns

In [9]:
#standardize column names(snake_case)
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [10]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,senior,365
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young,365
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,senior,365
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young,365
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,senior,14

In [11]:
#Remove redundant columns
df.drop(columns=['promo_code_used'], inplace=True,errors = 'ignore')

In [12]:
#Age Group
def age_group(age):
  if age < 25:
    return "Young"
  elif age < 45:
    return "Adult"
  else:
    return "senior"
df['age_group'] = df ['age'].apply(age_group)

In [13]:
#purchase_frequency_days
def freq_to_days(freq):
  if freq == 'weekly':
    return 7
  elif freq == 'monthly':
    return 30
  elif freq == 'Annually': # Added this condition based on 'Annually' in df.head()
    return 14
  else:
    return 365



df['purchase_frequency_days'] = df['frequency_of_purchases'].apply(freq_to_days)

In [14]:
#Validate Data Consistency
#check duplicates
df.duplicated().sum()

np.int64(0)

In [15]:
#Remove duplicates
df.drop_duplicates(inplace=True)

In [16]:
#Check data types
df.dtypes

customer_id                  int64
age                          int64
gender                      object
item_purchased              object
category                    object
purchase_amount              int64
location                    object
size                        object
color                       object
season                      object
review_rating              float64
subscription_status         object
shipping_type               object
discount_applied            object
previous_purchases           int64
payment_method              object
frequency_of_purchases      object
age_group                   object
purchase_frequency_days      int64
dtype: object

In [17]:
#Summery Statistics
df.describe()

,customer_id,age,purchase_amount,review_rating,previous_purchases,purchase_frequency_days
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750538,25.351538,313.520000
std,1125.977353,15.207589,23.685392,0.713589,14.447125,124.190355
min,1.000000,18.000000,20.000000,2.500000,1.000000,14.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000,365.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000,365.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000,365.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000,365.000000

In [18]:
#clean dataset
#save cleaned dataset
df.to_csv("cleaned_customer_data.csv",index=False)